### PR TITLE
Clean up repository

### PR DESCRIPTION
**Pull request by robertodr**
- Format C++, C, Fortran and Python sources
- Set up Git hooks for formatting and licensing info
- Document formatting and Git hooks in README.md
- Rename C++ headers to hpp
- Fix licensing headers
- Add AUTHORS.md and .mailmap
- Beautify CMakeLists.txt

**IMPORTANT** I removed `pyparsing.py`. I think it should rather be installed _via_ `pip` or `pipenv`.

### CODE REVIEW

**Comment by robertodr** [comment]
Ci coming up after this one is in.

**Comment by robertodr** [comment]
This can be squash-merged.

**Comment by bast** [comment]
I will not squash them, I prefer them separately in this case.

**Comment by robertodr** [comment]
Sorry, got carried away. I'll be more disciplined from now on.

**Pull request merged**
