### PR TITLE
Make FetchContent and config-mode consistent

### PR DESCRIPTION
**Pull request by robertodr**
This boils down to setting the `getkw_PYMOD` variable so that it can be picked up by projects using getkw with `FetchContent`.
`getkw_PYMOD` points to `${CMAKE_INSTALL_LIBDIR}/python` and inside that there's a `getkw` folder with a valid `__init__.py` I don't think we need to conform to the Python standard for installing packages as this is quite a different beast. Hence, the removal of the `find_package(PythonInterp` which was indeed only used to get the Python version.

### CODE REVIEW

**Comment by robertodr** [comment]
I suggest a squash-merge

**Comment by stigrj** [comment]
This works within the superbuild, but if I build `getkw` separately I get this error
```
CMake Warning (dev) at cmake/custom/getkw.cmake:63 (set):
  Cannot set "getkw_PYMOD": current scope has no parent.
Call Stack (most recent call first):
  CMakeLists.txt:57 (include)
```
originating from the last line in `cmake/custom/getkw.cmake`:
```
set(getkw_PYMOD ${PROJECT_BINARY_DIR}/${INSTALL_PYMODDIR} PARENT_SCOPE)
```
`Getkw` still compiles, but the Python modules are installed under `lib/python/getkw/` instead of `Python/lib/python3.7/site-packages`.

**Comment by stigrj** [comment]
Sorry, I didn't checkout the correct version of MRChem :man_facepalming: Now everything is working. There's still the `PARENT_SCOPE` warning when building separately, but that is probably fine.

**Comment by robertodr** [comment]
I've fixed the warning.

**Pull request merged**
