### PR TITLE
[WIP] Testing

### PR DESCRIPTION
**Pull request by robertodr**
- [ ] Use Catch as unit test framework.
- [ ] Add unit tests for C++ `Keyword`, `Section`, and `Getkw` classes.
- [ ] Add tests for Python parser.

### CODE REVIEW

**Review by bast — APPROVED** [review]
Looks good - I restarted the one stuck Travis runner.

**Comment by robertodr** [comment]
Well, I haven't written any tests yet LOL

**Comment by bast** [comment]
There is some testing going on but one Travis runner is stuck.

**Comment by robertodr** [comment]
I saw that... It's the one running the bot :( I'll look into it.

**Pull request closed without merging**
