### PR TITLE
Add Python tests

### PR DESCRIPTION
**Pull request by robertodr**
Does what it says on the tin. I moved the Python module from the `Python` folder to the `getkw` folder.

### CODE REVIEW

**Comment by bast** [comment]
Travis/pipenv is complaining. Are you looking into it?

**Comment by robertodr** [comment]
Not at the moment. I'll probably have time later tonight.

**Comment by robertodr** [comment]
"Tonight" never materialized, but given we're working on parselglossy, we can forget about it?

**Comment by bast** [comment]
It's fine for me to drop this.

**Pull request closed without merging**
